name: Build & Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - docs/**
  pull_request:
    branches:
      - main
    paths-ignore:
      - docs/**

jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup dotnet SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x.x'

    - name: Build solution
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test
