name: Release

on:
  release:
    types: [ published ]

jobs:
  build:
    name: Build, test, pack & publish to NuGet.org
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup dotnet SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x.x'

    - name: Parse tag name
      id: parsedTag
      uses: olegtarasov/get-tag@v2.1.4
      with:
        tagRegex: "(?<package>[a-zA-Z.]*)-(?<version>.*)"

    - name: Build solution
      run: dotnet build ./src/${{ steps.parsedTag.outputs.package }} --configuration Release

    - name: Run tests
      run: dotnet test ./tests/${{ steps.parsedTag.outputs.package}}.Tests --configuration Release

    - name: Pack NuGet packages
      run: dotnet pack ./src/${{ steps.parsedTag.outputs.package }} --configuration Release -p:PackageVersion=${{ steps.parsedTag.outputs.version }}
    
    - name: Push to NuGet.org
      run: dotnet nuget push "./src/${{ steps.parsedTag.outputs.package }}/**/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
