name: Release

on:
  release:
    types: [ published ]

jobs:
  build:
    name: Build, test, pack & publish to NuGet.org
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup dotnet SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x.x'

    - name: Build solution
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --configuration Release

    - name: Pack NuGet packages
      run: dotnet pack --configuration Release -p:PackageVersion=${{github.event.release.tag_name}}
    
    - name: Push to NuGet.org
      run: dotnet nuget push "**/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
